version: '3.8'

volumes:
  datafiles:
services:
  mysql:
    image: mysql:8.0.0
    container_name: mysql8
    environment:
      - MYSQL_DBHOST=mysql
      - MYSQL_DBPORT=3306
      - MYSQL_DBUSER=root
      - MYSQL_DBPASS=secret
      - MYSQL_DBNAME=auth
    volumes:
      - datafiles:/var/lib/mysql
    restart: always

  website:
    container_name: php73
    environment:
      - MYSQL_DBHOST=mysql
      - MYSQL_DBPORT=3306
      - MYSQL_DBUSER=root
      - MYSQL_DBPASS=secret
      - MYSQL_DBNAME=auth
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
      - 8083:443
    depends_on:
      - mysql #it means it depends on above service